language: python
python: 2.7
install:
  - pip install tox
env:
  - TOXENV=py26-django1.4
  - TOXENV=py26-django1.5
  - TOXENV=py26-django1.6
  - TOXENV=py27-django1.4
  - TOXENV=py27-django1.5
  - TOXENV=py27-django1.6
  - TOXENV=py33-django1.5
  - TOXENV=py33-django1.6
  - TOXENV=coverage
script:
  - tox -e $TOX_ENV
